// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjquCBUnkNmQ4yxNe27_YnVQ2VNYitJN4',
    appId: '1:64082819407:web:96f1c20bc2b165a305ed3a',
    messagingSenderId: '64082819407',
    projectId: 'reddit-clone-77dfc',
    authDomain: 'reddit-clone-77dfc.firebaseapp.com',
    storageBucket: 'reddit-clone-77dfc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMGod_85HcpMi6976Gi9g5XsOUYEA7P9g',
    appId: '1:64082819407:android:8159869b11a66ca405ed3a',
    messagingSenderId: '64082819407',
    projectId: 'reddit-clone-77dfc',
    storageBucket: 'reddit-clone-77dfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJK62wxGZm8QvR2FdUoerrVbCOoOkVB70',
    appId: '1:64082819407:ios:aba349da2bf5149205ed3a',
    messagingSenderId: '64082819407',
    projectId: 'reddit-clone-77dfc',
    storageBucket: 'reddit-clone-77dfc.appspot.com',
    iosClientId: '64082819407-ntvdqobk2jp91qr41c4dcg1qmfvil055.apps.googleusercontent.com',
    iosBundleId: 'com.dazai.redditClone',
  );
}
